[[Auth-API]]
== 1. Auth API

[[로그인]]
=== 1.1.1. 로그인 성공
operation::auth-controller-test/로그인[snippets='http-request,http-response,request-fields']

=== 1.1.2. 로그인 실패 (잘못된 지갑 주소)
operation::auth-controller-test/로그인_실패_잘못된_지갑주소[snippets='http-request,http-response,request-fields']

[[회원가입]]
=== 1.2.1. 회원가입
operation::auth-controller-test/회원가입[snippets='http-request,http-response,request-fields']

[[회원가입_실패_이미가입되어있는경우]]
=== 1.2.2. 회원가입 실패 (이미 가입되어 있는 경우)
operation::auth-controller-test/회원가입_실패_이미_가입되어있는_경우[snippets='http-request,http-response,request-fields']

[[회원가입_실패_잘못된_요청값]]
=== 1.2.3 회원가입 실패 (잘못된 요청 값)
operation::auth-controller-test/회원가입_실패[snippets='http-request,http-response,request-fields']

[[토큰_재발행]]
=== 1.3.1. 토큰 재발행
operation::auth-controller-test/토큰_재발행[snippets='http-request,http-response,request-fields']

[[토큰_재발행_실패]]
=== 1.3.2. 토큰 재발행 실패
operation::auth-controller-test/토큰_재발행_실패[snippets='http-request,http-response,request-fields']

[[로그아웃]]
=== 1.4. 로그아웃
operation::auth-controller-test/로그아웃[snippets='http-request,http-response']


[[닉네임_중복검사]]
=== 1.5.1. 닉네임 중복검사
operation::auth-controller-test/닉네임_중복_검사[snippets='http-request,http-response,path-parameters']

=== 1.5.2. 닉네임 중복검사(닉네임 중복일 경우)
operation::auth-controller-test/닉네임_중복_검사_실패[snippets='http-request,http-response,path-parameters']
